package com.steer.data.webservice.rfidsoap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-11-21T08:34:12.837+08:00
 * Generated source version: 3.2.6
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IRfidService")
@XmlSeeAlso({ObjectFactory.class})
public interface IRfidService {

    @WebMethod(operationName = "Write_BatchLotLet", action = "http://tempuri.org/IRfidService/Write_BatchLotLet")
    @Action(input = "http://tempuri.org/IRfidService/Write_BatchLotLet", output = "http://tempuri.org/IRfidService/Write_BatchLotLetResponse")
    @RequestWrapper(localName = "Write_BatchLotLet", targetNamespace = "http://tempuri.org/", className = "com.steer.data.webservice.rfidsoap.WriteBatchLotLet")
    @ResponseWrapper(localName = "Write_BatchLotLetResponse", targetNamespace = "http://tempuri.org/", className = "com.steer.data.webservice.rfidsoap.WriteBatchLotLetResponse")
    @WebResult(name = "Write_BatchLotLetResult", targetNamespace = "http://tempuri.org/")
    java.lang.String writeBatchLotLet(
            @WebParam(name = "str_Batch_Lot_Let", targetNamespace = "http://tempuri.org/")
                    java.lang.String strBatchLotLet
    );

    @WebMethod(operationName = "Write_BatchLotLet_One_Record", action = "http://tempuri.org/IRfidService/Write_BatchLotLet_One_Record")
    @Action(input = "http://tempuri.org/IRfidService/Write_BatchLotLet_One_Record", output = "http://tempuri.org/IRfidService/Write_BatchLotLet_One_RecordResponse")
    @RequestWrapper(localName = "Write_BatchLotLet_One_Record", targetNamespace = "http://tempuri.org/", className = "com.steer.data.webservice.rfidsoap.WriteBatchLotLetOneRecord")
    @ResponseWrapper(localName = "Write_BatchLotLet_One_RecordResponse", targetNamespace = "http://tempuri.org/", className = "com.steer.data.webservice.rfidsoap.WriteBatchLotLetOneRecordResponse")
    @WebResult(name = "Write_BatchLotLet_One_RecordResult", targetNamespace = "http://tempuri.org/")
    java.lang.String writeBatchLotLetOneRecord(
            @WebParam(name = "i_batch_8", targetNamespace = "http://tempuri.org/")
                    java.lang.Long iBatch8,
            @WebParam(name = "i_Lot_8", targetNamespace = "http://tempuri.org/")
                    java.lang.Integer iLot8,
            @WebParam(name = "i_gangzhong_8", targetNamespace = "http://tempuri.org/")
                    java.lang.Integer iGangzhong8
    );

    @WebMethod(operationName = "Get_RFID_Data_XML_String", action = "http://tempuri.org/IRfidService/Get_RFID_Data_XML_String")
    @Action(input = "http://tempuri.org/IRfidService/Get_RFID_Data_XML_String", output = "http://tempuri.org/IRfidService/Get_RFID_Data_XML_StringResponse")
    @RequestWrapper(localName = "Get_RFID_Data_XML_String", targetNamespace = "http://tempuri.org/", className = "com.steer.data.webservice.rfidsoap.GetRFIDDataXMLString")
    @ResponseWrapper(localName = "Get_RFID_Data_XML_StringResponse", targetNamespace = "http://tempuri.org/", className = "com.steer.data.webservice.rfidsoap.GetRFIDDataXMLStringResponse")
    @WebResult(name = "Get_RFID_Data_XML_StringResult", targetNamespace = "http://tempuri.org/")
    java.lang.String getRFIDDataXMLString();

    @WebMethod(operationName = "Get_XinTiao_Int", action = "http://tempuri.org/IRfidService/Get_XinTiao_Int")
    @Action(input = "http://tempuri.org/IRfidService/Get_XinTiao_Int", output = "http://tempuri.org/IRfidService/Get_XinTiao_IntResponse")
    @RequestWrapper(localName = "Get_XinTiao_Int", targetNamespace = "http://tempuri.org/", className = "com.steer.data.webservice.rfidsoap.GetXinTiaoInt")
    @ResponseWrapper(localName = "Get_XinTiao_IntResponse", targetNamespace = "http://tempuri.org/", className = "com.steer.data.webservice.rfidsoap.GetXinTiaoIntResponse")
    @WebResult(name = "Get_XinTiao_IntResult", targetNamespace = "http://tempuri.org/")
    java.lang.Integer getXinTiaoInt();

    @WebMethod(operationName = "Get_RFID_Data_Json_String", action = "http://tempuri.org/IRfidService/Get_RFID_Data_Json_String")
    @Action(input = "http://tempuri.org/IRfidService/Get_RFID_Data_Json_String", output = "http://tempuri.org/IRfidService/Get_RFID_Data_Json_StringResponse")
    @RequestWrapper(localName = "Get_RFID_Data_Json_String", targetNamespace = "http://tempuri.org/", className = "com.steer.data.webservice.rfidsoap.GetRFIDDataJsonString")
    @ResponseWrapper(localName = "Get_RFID_Data_Json_StringResponse", targetNamespace = "http://tempuri.org/", className = "com.steer.data.webservice.rfidsoap.GetRFIDDataJsonStringResponse")
    @WebResult(name = "Get_RFID_Data_Json_StringResult", targetNamespace = "http://tempuri.org/")
    java.lang.String getRFIDDataJsonString();
}
