
package com.steer.data.webservice.rfidsoap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-11-21T08:34:12.806+08:00
 * Generated source version: 3.2.6
 */
public final class IRfidService_BasicHttpBindingIRfidService_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "RfidService");

    private IRfidService_BasicHttpBindingIRfidService_Client() {
    }

    public static void main(String[] args) throws java.lang.Exception {
        URL wsdlURL = RfidService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        RfidService ss = new RfidService(wsdlURL, SERVICE_NAME);
        IRfidService port = ss.getBasicHttpBindingIRfidService();

        {
            System.out.println("Invoking writeBatchLotLet...");
            java.lang.String _writeBatchLotLet_strBatchLotLet = "";
            java.lang.String _writeBatchLotLet__return = port.writeBatchLotLet(_writeBatchLotLet_strBatchLotLet);
            System.out.println("writeBatchLotLet.result=" + _writeBatchLotLet__return);


        }
        {
            System.out.println("Invoking writeBatchLotLetOneRecord...");
            java.lang.Long _writeBatchLotLetOneRecord_iBatch8 = null;
            java.lang.Integer _writeBatchLotLetOneRecord_iLot8 = null;
            java.lang.Integer _writeBatchLotLetOneRecord_iGangzhong8 = null;
            java.lang.String _writeBatchLotLetOneRecord__return = port.writeBatchLotLetOneRecord(_writeBatchLotLetOneRecord_iBatch8, _writeBatchLotLetOneRecord_iLot8, _writeBatchLotLetOneRecord_iGangzhong8);
            System.out.println("writeBatchLotLetOneRecord.result=" + _writeBatchLotLetOneRecord__return);


        }
        {
            System.out.println("Invoking getRFIDDataXMLString...");
            java.lang.String _getRFIDDataXMLString__return = port.getRFIDDataXMLString();
            System.out.println("getRFIDDataXMLString.result=" + _getRFIDDataXMLString__return);


        }
        {
            System.out.println("Invoking getXinTiaoInt...");
            java.lang.Integer _getXinTiaoInt__return = port.getXinTiaoInt();
            System.out.println("getXinTiaoInt.result=" + _getXinTiaoInt__return);


        }
        {
            System.out.println("Invoking getRFIDDataJsonString...");
            java.lang.String _getRFIDDataJsonString__return = port.getRFIDDataJsonString();
            System.out.println("getRFIDDataJsonString.result=" + _getRFIDDataJsonString__return);


        }

        System.exit(0);
    }

}
