package com.steer.data.webservice.rfidsoap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-11-21T08:34:12.853+08:00
 * Generated source version: 3.2.6
 */
@WebServiceClient(name = "RfidService",
        wsdlLocation = "http://172.16.21.166:8730/RfidService?wsdl",
        targetNamespace = "http://tempuri.org/")
public class RfidService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "RfidService");
    public final static QName BasicHttpBindingIRfidService = new QName("http://tempuri.org/", "BasicHttpBinding_IRfidService");

    static {
        URL url = null;
        try {
            url = new URL("http://172.16.21.166:8730/RfidService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RfidService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "http://172.16.21.166:8730/RfidService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RfidService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RfidService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RfidService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public RfidService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RfidService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RfidService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     * @return returns IRfidService
     */
    @WebEndpoint(name = "BasicHttpBinding_IRfidService")
    public IRfidService getBasicHttpBindingIRfidService() {
        return super.getPort(BasicHttpBindingIRfidService, IRfidService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns IRfidService
     */
    @WebEndpoint(name = "BasicHttpBinding_IRfidService")
    public IRfidService getBasicHttpBindingIRfidService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIRfidService, IRfidService.class, features);
    }

}
