package com.steer.data.webservice.plm.wgt.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-11-12T14:40:51.372+08:00
 * Generated source version: 3.2.6
 */
@WebService(targetNamespace = "http://service.wgt.plm.com/", name = "MesPlmL2WgtService")
@XmlSeeAlso({
        //ObjectFactory.class
})
public interface MesPlmL2WgtService {

    @WebMethod
    @RequestWrapper(localName = "insertACCEPT", targetNamespace = "http://service.wgt.plm.com/", className = "com.plm.wgt.service.InsertACCEPT")
    @ResponseWrapper(localName = "insertACCEPTResponse", targetNamespace = "http://service.wgt.plm.com/", className = "com.plm.wgt.service.InsertACCEPTResponse")
    @WebResult(name = "return", targetNamespace = "")
    java.lang.String insertACCEPT(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.lang.String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    java.lang.Double arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    java.lang.Double arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    java.lang.String arg4,
            @WebParam(name = "arg5", targetNamespace = "")
                    java.lang.String arg5,
            @WebParam(name = "arg6", targetNamespace = "")
                    int arg6,
            @WebParam(name = "arg7", targetNamespace = "")
                    int arg7
    );
}
